language: c

env:
    - MPI_IMPL=openmpi

before_install:
    - test -n $CC && unset CC
    - sh ./travis-install-mpi.sh $MPI_IMPL
    - export PATH=$HOME/OpenMPI/bin:$PATH

script:
    - mpicc mpi_pi_reduce.c -o mpi_pi_reduce

